export type RootStackParamList = {
  Landing: undefined;
  Registration: undefined;
  PendingApproval: undefined;
  Rejected: { message?: string };
  Login: undefined;
  GoogleCompleteProfile: undefined;
  SetUsername: undefined;
  SearchMembers: { context?: "messages" } | undefined;
  Connections: undefined;
  MemberProfile: { userId?: number; username?: string };
  OtpVerify: { email: string };
  Home: undefined;
  Profile: undefined;
  EditProfile: undefined;
  MyPosts: undefined;
  MyActivity: undefined;
  PostDetail: { postId: number };
  CreatePost: { initialPostType?: string; editPostId?: number } | undefined;
  Menu: { messageCount?: number };
  Settings: undefined;
  Messages: undefined;
  Chat: {
    otherUserId: number;
    name: string;
    profileImage?: string | null;
    online?: boolean;
  };
  JobsHome: undefined;
  MarketplaceHome: undefined;
  HelpingHandsHome: undefined;
  CreateHelpRequest: undefined;
  MatrimonyHome: undefined;
  MatrimonySetup: undefined;
  MatrimonyBrowse: undefined;
  MatrimonyCandidate: { userId: number; interestId?: number; fromWhoViewedMe?: boolean };
  MatrimonyInterests: undefined;
  MatrimonyMatches: undefined;
  MatrimonySaved: undefined;
  MatrimonyPlans: undefined;
  MatrimonyMySubscription: undefined;
  MatrimonyViews: undefined;
  Notifications: undefined;
  HelpSupport: undefined;
  SupportFaqs: undefined;
  SupportGuides: undefined;
  SupportGuideDetail: { guideId: number };
  SupportContact: undefined;
  SupportCreateTicket: { type?: "BUG" | "FEATURE" | "QUESTION" | "CONTACT" | "GENERAL" } | undefined;
  SupportMyTickets: undefined;
  SupportTicketDetail: { ticketId: number };
};
